/**
 * Global size conversion data.
 *
 * Transcribed verbatim from the supplied `global_size_guide_complete.json` and
 * checked in as code so that the storefront, the API and the static demo build
 * all read one copy. Nothing here is derived, interpolated or extended: a size
 * that is not in the source is not in the shop's size guide, and a product type
 * with no chart shows no guide at all.
 *
 * GENERATED FILE — regenerate rather than edit by hand if the source JSON is
 * replaced. Column keys are the source's own; `SIZE_COLUMN_LABELS` in
 * ./size-guide.ts is the only place they are given human names.
 */

import type { TargetGroup } from '@outlet/types';

export interface SizeChartRow {
  [column: string]: string;
}

export interface SizeChartData {
  /** `men.jeans_and_trousers` — audience and product type, as the source keys them. */
  id: string;
  audience: TargetGroup;
  /** The source's product-type key, e.g. `tshirts_and_casual`. */
  type: string;
  name: string;
  /** The source's own description of what the numbers mean. */
  unitSystem: string;
  /** Column keys in source order; every row is keyed by these. */
  columns: string[];
  rows: SizeChartRow[];
}

/** Every column key that appears anywhere in the data. */
export const SIZE_CHART_COLUMN_KEYS = [
  'international',
  'US_UK',
  'EU',
  'IT',
  'FR',
  'JP',
  'chest_cm',
  'chest_in',
  'collar_inches_US_UK',
  'collar_cm_EU_IT_FR',
  'jeans_waist',
  'waist_cm',
  'US',
  'UK',
  'bust_cm',
  'bust_in',
  'waist_in',
  'age',
  'height_cm',
  'unisex_size',
  'mens_size',
  'womens_size',
  'US_Men',
  'US_Women',
  'EU_Men',
  'EU_Women',
  'IT_Men',
  'IT_Women',
] as const;

export const SIZE_GUIDE_METADATA = {
  title: 'Comprehensive Global Clothing Size Guide',
  version: '2.0',
  description:
    'Full sizing conversion matrix for Men, Women, Kids, and Unisex across T-shirts, Shirts, and Jeans/Trousers for US, UK, EU, IT, FR, and JP regions.',
  noteOnItVsEu:
    "In Women's sizing, Italian (IT) sizes are typically 6 numbers higher than standard European (EU) sizes (e.g., EU 36 = IT 42). In French (FR) sizing, it is 2 numbers higher than EU (e.g., EU 36 = FR 38).",
};

export const SIZE_CHARTS: SizeChartData[] = [
  {
    id: 'men.tshirts_and_casual',
    audience: 'MEN',
    type: 'tshirts_and_casual',
    name: 'T-Shirts & Casual',
    unitSystem: 'Alpha & Numeric Chest',
    columns: ['international', 'US_UK', 'EU', 'IT', 'FR', 'JP', 'chest_cm', 'chest_in'],
    rows: [
      {
        international: 'XXS',
        US_UK: '32',
        EU: '42',
        IT: '42',
        FR: '42',
        JP: 'XS',
        chest_cm: '81-86',
        chest_in: '32-34',
      },
      {
        international: 'XS',
        US_UK: '34',
        EU: '44',
        IT: '44',
        FR: '44',
        JP: 'S',
        chest_cm: '86-91',
        chest_in: '34-36',
      },
      {
        international: 'S',
        US_UK: '36',
        EU: '46',
        IT: '46',
        FR: '46',
        JP: 'M',
        chest_cm: '91-96',
        chest_in: '36-38',
      },
      {
        international: 'M',
        US_UK: '38',
        EU: '48',
        IT: '48',
        FR: '48',
        JP: 'L',
        chest_cm: '96-101',
        chest_in: '38-40',
      },
      {
        international: 'L',
        US_UK: '40',
        EU: '50',
        IT: '50',
        FR: '50',
        JP: 'XL',
        chest_cm: '101-106',
        chest_in: '40-42',
      },
      {
        international: 'XL',
        US_UK: '42',
        EU: '52',
        IT: '52',
        FR: '52',
        JP: 'XXL',
        chest_cm: '106-111',
        chest_in: '42-44',
      },
      {
        international: 'XXL',
        US_UK: '44',
        EU: '54',
        IT: '54',
        FR: '54',
        JP: '3XL',
        chest_cm: '111-116',
        chest_in: '44-46',
      },
      {
        international: '3XL',
        US_UK: '46',
        EU: '56',
        IT: '56',
        FR: '56',
        JP: '4XL',
        chest_cm: '116-121',
        chest_in: '46-48',
      },
      {
        international: '4XL',
        US_UK: '48',
        EU: '58',
        IT: '58',
        FR: '58',
        JP: '5XL',
        chest_cm: '121-126',
        chest_in: '48-50',
      },
      {
        international: '5XL',
        US_UK: '50',
        EU: '60',
        IT: '60',
        FR: '60',
        JP: '6XL',
        chest_cm: '126-131',
        chest_in: '50-52',
      },
    ],
  },
  {
    id: 'men.shirts',
    audience: 'MEN',
    type: 'shirts',
    name: 'Shirts',
    unitSystem: 'Collar Size',
    columns: ['international', 'collar_inches_US_UK', 'collar_cm_EU_IT_FR'],
    rows: [
      {
        international: 'XXS',
        collar_inches_US_UK: '13.5',
        collar_cm_EU_IT_FR: '34',
      },
      {
        international: 'XS',
        collar_inches_US_UK: '14.0',
        collar_cm_EU_IT_FR: '35-36',
      },
      {
        international: 'S',
        collar_inches_US_UK: '14.5',
        collar_cm_EU_IT_FR: '37',
      },
      {
        international: 'S',
        collar_inches_US_UK: '15.0',
        collar_cm_EU_IT_FR: '38',
      },
      {
        international: 'M',
        collar_inches_US_UK: '15.5',
        collar_cm_EU_IT_FR: '39-40',
      },
      {
        international: 'M',
        collar_inches_US_UK: '16.0',
        collar_cm_EU_IT_FR: '41',
      },
      {
        international: 'L',
        collar_inches_US_UK: '16.5',
        collar_cm_EU_IT_FR: '42',
      },
      {
        international: 'L',
        collar_inches_US_UK: '17.0',
        collar_cm_EU_IT_FR: '43',
      },
      {
        international: 'XL',
        collar_inches_US_UK: '17.5',
        collar_cm_EU_IT_FR: '44',
      },
      {
        international: 'XL',
        collar_inches_US_UK: '18.0',
        collar_cm_EU_IT_FR: '45-46',
      },
      {
        international: 'XXL',
        collar_inches_US_UK: '18.5',
        collar_cm_EU_IT_FR: '47',
      },
      {
        international: '3XL',
        collar_inches_US_UK: '19.0',
        collar_cm_EU_IT_FR: '48-49',
      },
    ],
  },
  {
    id: 'men.jeans_and_trousers',
    audience: 'MEN',
    type: 'jeans_and_trousers',
    name: 'Jeans & Trousers',
    unitSystem: 'Waist Inches & Regional Numerical',
    columns: ['jeans_waist', 'US_UK', 'EU', 'IT', 'FR', 'JP', 'waist_cm'],
    rows: [
      {
        jeans_waist: 'W26',
        US_UK: '26',
        EU: '42',
        IT: '42',
        FR: '34',
        JP: '66',
        waist_cm: '66-68',
      },
      {
        jeans_waist: 'W27',
        US_UK: '27',
        EU: '43',
        IT: '43',
        FR: '35',
        JP: '68',
        waist_cm: '68-71',
      },
      {
        jeans_waist: 'W28',
        US_UK: '28',
        EU: '44',
        IT: '44',
        FR: '36',
        JP: '71',
        waist_cm: '71-73',
      },
      {
        jeans_waist: 'W29',
        US_UK: '29',
        EU: '45',
        IT: '45',
        FR: '37',
        JP: '73',
        waist_cm: '73-76',
      },
      {
        jeans_waist: 'W30',
        US_UK: '30',
        EU: '46',
        IT: '46',
        FR: '38',
        JP: '76',
        waist_cm: '76-78',
      },
      {
        jeans_waist: 'W31',
        US_UK: '31',
        EU: '47',
        IT: '47',
        FR: '39',
        JP: '78',
        waist_cm: '78-81',
      },
      {
        jeans_waist: 'W32',
        US_UK: '32',
        EU: '48',
        IT: '48',
        FR: '40',
        JP: '81',
        waist_cm: '81-83',
      },
      {
        jeans_waist: 'W33',
        US_UK: '33',
        EU: '49',
        IT: '49',
        FR: '41',
        JP: '83',
        waist_cm: '83-86',
      },
      {
        jeans_waist: 'W34',
        US_UK: '34',
        EU: '50',
        IT: '50',
        FR: '42',
        JP: '86',
        waist_cm: '86-88',
      },
      {
        jeans_waist: 'W36',
        US_UK: '36',
        EU: '52',
        IT: '52',
        FR: '44',
        JP: '91',
        waist_cm: '91-94',
      },
      {
        jeans_waist: 'W38',
        US_UK: '38',
        EU: '54',
        IT: '54',
        FR: '46',
        JP: '96',
        waist_cm: '96-99',
      },
      {
        jeans_waist: 'W40',
        US_UK: '40',
        EU: '56',
        IT: '56',
        FR: '48',
        JP: '101',
        waist_cm: '101-104',
      },
      {
        jeans_waist: 'W42',
        US_UK: '42',
        EU: '58',
        IT: '58',
        FR: '50',
        JP: '106',
        waist_cm: '106-109',
      },
      {
        jeans_waist: 'W44',
        US_UK: '44',
        EU: '60',
        IT: '60',
        FR: '52',
        JP: '111',
        waist_cm: '111-114',
      },
    ],
  },
  {
    id: 'women.tshirts_and_casual',
    audience: 'WOMEN',
    type: 'tshirts_and_casual',
    name: 'T-Shirts & Casual',
    unitSystem: 'Alpha & Regional Dress Sizes',
    columns: ['international', 'US', 'UK', 'EU', 'IT', 'FR', 'JP', 'bust_cm', 'bust_in'],
    rows: [
      {
        international: 'XXXS',
        US: '00',
        UK: '2',
        EU: '28',
        IT: '34',
        FR: '30',
        JP: '3',
        bust_cm: '72-75',
        bust_in: '28-29',
      },
      {
        international: 'XXS',
        US: '0',
        UK: '4',
        EU: '30',
        IT: '36',
        FR: '32',
        JP: '5',
        bust_cm: '76-79',
        bust_in: '30-31',
      },
      {
        international: 'XS',
        US: '2',
        UK: '6',
        EU: '32',
        IT: '38',
        FR: '34',
        JP: '7',
        bust_cm: '80-83',
        bust_in: '31-32',
      },
      {
        international: 'S',
        US: '4',
        UK: '8',
        EU: '34',
        IT: '40',
        FR: '36',
        JP: '9',
        bust_cm: '84-87',
        bust_in: '33-34',
      },
      {
        international: 'M',
        US: '6',
        UK: '10',
        EU: '36',
        IT: '42',
        FR: '38',
        JP: '11',
        bust_cm: '88-91',
        bust_in: '35-36',
      },
      {
        international: 'L',
        US: '8',
        UK: '12',
        EU: '38',
        IT: '44',
        FR: '40',
        JP: '13',
        bust_cm: '92-95',
        bust_in: '36-37',
      },
      {
        international: 'XL',
        US: '10',
        UK: '14',
        EU: '40',
        IT: '46',
        FR: '42',
        JP: '15',
        bust_cm: '96-99',
        bust_in: '38-39',
      },
      {
        international: 'XXL',
        US: '12',
        UK: '16',
        EU: '42',
        IT: '48',
        FR: '44',
        JP: '17',
        bust_cm: '100-103',
        bust_in: '39-40',
      },
      {
        international: '3XL',
        US: '14',
        UK: '18',
        EU: '44',
        IT: '50',
        FR: '46',
        JP: '19',
        bust_cm: '104-108',
        bust_in: '41-42',
      },
      {
        international: '4XL',
        US: '16',
        UK: '20',
        EU: '46',
        IT: '52',
        FR: '48',
        JP: '21',
        bust_cm: '109-113',
        bust_in: '43-44',
      },
      {
        international: '5XL',
        US: '18',
        UK: '22',
        EU: '48',
        IT: '54',
        FR: '50',
        JP: '23',
        bust_cm: '114-118',
        bust_in: '45-46',
      },
    ],
  },
  {
    id: 'women.shirts_and_blouses',
    audience: 'WOMEN',
    type: 'shirts_and_blouses',
    name: 'Shirts & Blouses',
    unitSystem: 'Regional Numerical Sizing',
    columns: ['international', 'US', 'UK', 'EU', 'IT', 'FR', 'JP'],
    rows: [
      {
        international: 'XXS',
        US: '0',
        UK: '4',
        EU: '30',
        IT: '36',
        FR: '32',
        JP: '5',
      },
      {
        international: 'XS',
        US: '2',
        UK: '6',
        EU: '32',
        IT: '38',
        FR: '34',
        JP: '7',
      },
      {
        international: 'S',
        US: '4',
        UK: '8',
        EU: '34',
        IT: '40',
        FR: '36',
        JP: '9',
      },
      {
        international: 'M',
        US: '6',
        UK: '10',
        EU: '36',
        IT: '42',
        FR: '38',
        JP: '11',
      },
      {
        international: 'L',
        US: '8',
        UK: '12',
        EU: '38',
        IT: '44',
        FR: '40',
        JP: '13',
      },
      {
        international: 'XL',
        US: '10',
        UK: '14',
        EU: '40',
        IT: '46',
        FR: '42',
        JP: '15',
      },
      {
        international: 'XXL',
        US: '12',
        UK: '16',
        EU: '42',
        IT: '48',
        FR: '44',
        JP: '17',
      },
      {
        international: '3XL',
        US: '14',
        UK: '18',
        EU: '44',
        IT: '50',
        FR: '46',
        JP: '19',
      },
      {
        international: '4XL',
        US: '16',
        UK: '20',
        EU: '46',
        IT: '52',
        FR: '48',
        JP: '21',
      },
    ],
  },
  {
    id: 'women.jeans_and_trousers',
    audience: 'WOMEN',
    type: 'jeans_and_trousers',
    name: 'Jeans & Trousers',
    unitSystem: 'Waist Inches vs Regional Numerical (Highlights IT vs EU differences)',
    columns: ['jeans_waist', 'US', 'UK', 'EU', 'IT', 'FR', 'JP', 'waist_cm', 'waist_in'],
    rows: [
      {
        jeans_waist: 'W23',
        US: '00',
        UK: '2',
        EU: '28',
        IT: '34',
        FR: '30',
        JP: '3',
        waist_cm: '58-60',
        waist_in: '23',
      },
      {
        jeans_waist: 'W24',
        US: '0',
        UK: '4',
        EU: '30',
        IT: '36',
        FR: '32',
        JP: '5',
        waist_cm: '61-63',
        waist_in: '24',
      },
      {
        jeans_waist: 'W25',
        US: '2',
        UK: '6',
        EU: '32',
        IT: '38',
        FR: '34',
        JP: '7',
        waist_cm: '64-66',
        waist_in: '25',
      },
      {
        jeans_waist: 'W26',
        US: '4',
        UK: '8',
        EU: '34',
        IT: '40',
        FR: '36',
        JP: '9',
        waist_cm: '67-69',
        waist_in: '26',
      },
      {
        jeans_waist: 'W27',
        US: '6',
        UK: '10',
        EU: '36',
        IT: '42',
        FR: '38',
        JP: '11',
        waist_cm: '70-72',
        waist_in: '27',
      },
      {
        jeans_waist: 'W28',
        US: '8',
        UK: '12',
        EU: '38',
        IT: '44',
        FR: '40',
        JP: '13',
        waist_cm: '73-75',
        waist_in: '28',
      },
      {
        jeans_waist: 'W29',
        US: '10',
        UK: '14',
        EU: '40',
        IT: '46',
        FR: '42',
        JP: '15',
        waist_cm: '76-78',
        waist_in: '29',
      },
      {
        jeans_waist: 'W30',
        US: '12',
        UK: '16',
        EU: '42',
        IT: '48',
        FR: '44',
        JP: '17',
        waist_cm: '79-81',
        waist_in: '30',
      },
      {
        jeans_waist: 'W31',
        US: '14',
        UK: '18',
        EU: '44',
        IT: '50',
        FR: '46',
        JP: '19',
        waist_cm: '82-84',
        waist_in: '31',
      },
      {
        jeans_waist: 'W32',
        US: '16',
        UK: '20',
        EU: '46',
        IT: '52',
        FR: '48',
        JP: '21',
        waist_cm: '85-88',
        waist_in: '32',
      },
      {
        jeans_waist: 'W33',
        US: '18',
        UK: '22',
        EU: '48',
        IT: '54',
        FR: '50',
        JP: '23',
        waist_cm: '89-92',
        waist_in: '33',
      },
      {
        jeans_waist: 'W34',
        US: '20',
        UK: '24',
        EU: '50',
        IT: '56',
        FR: '52',
        JP: '25',
        waist_cm: '93-96',
        waist_in: '34',
      },
    ],
  },
  {
    id: 'kids.all_clothing',
    audience: 'KIDS',
    type: 'all_clothing',
    name: 'All Clothing',
    unitSystem: 'Age and Height (CM)',
    columns: ['age', 'height_cm', 'US', 'UK', 'EU', 'IT', 'JP'],
    rows: [
      {
        age: '0-3 Months',
        height_cm: '56-62',
        US: '3M',
        UK: '0-3m',
        EU: '56-62',
        IT: '56-62',
        JP: '60',
      },
      {
        age: '3-6 Months',
        height_cm: '62-68',
        US: '6M',
        UK: '3-6m',
        EU: '62-68',
        IT: '62-68',
        JP: '70',
      },
      {
        age: '6-12 Months',
        height_cm: '68-80',
        US: '12M',
        UK: '6-12m',
        EU: '68-80',
        IT: '68-80',
        JP: '80',
      },
      {
        age: '12-18 Months',
        height_cm: '80-86',
        US: '18M',
        UK: '12-18m',
        EU: '80-86',
        IT: '80-86',
        JP: '85',
      },
      {
        age: '2 Years',
        height_cm: '86-92',
        US: '2T',
        UK: '2Y',
        EU: '92',
        IT: '92',
        JP: '90',
      },
      {
        age: '3 Years',
        height_cm: '92-98',
        US: '3T',
        UK: '3Y',
        EU: '98',
        IT: '98',
        JP: '100',
      },
      {
        age: '4 Years',
        height_cm: '98-104',
        US: '4T',
        UK: '4Y',
        EU: '104',
        IT: '104',
        JP: '110',
      },
      {
        age: '5 Years',
        height_cm: '104-110',
        US: '5',
        UK: '5Y',
        EU: '110',
        IT: '110',
        JP: '110',
      },
      {
        age: '6 Years',
        height_cm: '110-116',
        US: '6',
        UK: '6Y',
        EU: '116',
        IT: '116',
        JP: '120',
      },
      {
        age: '7-8 Years',
        height_cm: '122-128',
        US: '7-8',
        UK: '7-8Y',
        EU: '122-128',
        IT: '122-128',
        JP: '130',
      },
      {
        age: '9-10 Years',
        height_cm: '134-140',
        US: '10',
        UK: '9-10Y',
        EU: '134-140',
        IT: '134-140',
        JP: '140',
      },
      {
        age: '11-12 Years',
        height_cm: '146-152',
        US: '12',
        UK: '11-12Y',
        EU: '146-152',
        IT: '146-152',
        JP: '150',
      },
      {
        age: '13-14 Years',
        height_cm: '158-164',
        US: '14',
        UK: '13-14Y',
        EU: '158-164',
        IT: '158-164',
        JP: '160',
      },
    ],
  },
  {
    id: 'unisex.tshirts_and_casual',
    audience: 'UNISEX',
    type: 'tshirts_and_casual',
    name: 'T-Shirts & Casual',
    unitSystem: 'Unisex Alpha Sizing Matrix',
    columns: [
      'unisex_size',
      'mens_size',
      'womens_size',
      'US_Men',
      'US_Women',
      'EU_Men',
      'EU_Women',
      'IT_Men',
      'IT_Women',
    ],
    rows: [
      {
        unisex_size: 'XXS',
        mens_size: 'XXS',
        womens_size: 'XS',
        US_Men: '32',
        US_Women: '2',
        EU_Men: '42',
        EU_Women: '32',
        IT_Men: '42',
        IT_Women: '38',
      },
      {
        unisex_size: 'XS',
        mens_size: 'XS',
        womens_size: 'S',
        US_Men: '34',
        US_Women: '4',
        EU_Men: '44',
        EU_Women: '34',
        IT_Men: '44',
        IT_Women: '40',
      },
      {
        unisex_size: 'S',
        mens_size: 'S',
        womens_size: 'M',
        US_Men: '36',
        US_Women: '6',
        EU_Men: '46',
        EU_Women: '36',
        IT_Men: '46',
        IT_Women: '42',
      },
      {
        unisex_size: 'M',
        mens_size: 'M',
        womens_size: 'L',
        US_Men: '38',
        US_Women: '8',
        EU_Men: '48',
        EU_Women: '38',
        IT_Men: '48',
        IT_Women: '44',
      },
      {
        unisex_size: 'L',
        mens_size: 'L',
        womens_size: 'XL',
        US_Men: '40',
        US_Women: '10',
        EU_Men: '50',
        EU_Women: '40',
        IT_Men: '50',
        IT_Women: '46',
      },
      {
        unisex_size: 'XL',
        mens_size: 'XL',
        womens_size: 'XXL',
        US_Men: '42',
        US_Women: '12',
        EU_Men: '52',
        EU_Women: '42',
        IT_Men: '52',
        IT_Women: '48',
      },
      {
        unisex_size: 'XXL',
        mens_size: 'XXL',
        womens_size: '3XL',
        US_Men: '44',
        US_Women: '14',
        EU_Men: '54',
        EU_Women: '44',
        IT_Men: '54',
        IT_Women: '50',
      },
      {
        unisex_size: '3XL',
        mens_size: '3XL',
        womens_size: '4XL',
        US_Men: '46',
        US_Women: '16',
        EU_Men: '56',
        EU_Women: '46',
        IT_Men: '56',
        IT_Women: '52',
      },
    ],
  },
];
