/**
 * Brands, the category tree, campaigns, reviews and CMS pages.
 *
 * The rule the tree follows, carried over from the PostgreSQL API: a category
 * reaches a customer only when it is active, all of its ancestors are active,
 * and it holds at least one available product. So a subcategory that sells out
 * drops off the menu on its own and comes back when stock is published, while
 * one an administrator switched off stays off until they switch it back. The
 * two conditions are reported separately to the admin panel (`Hidden` vs
 * `Empty`) because conflating them would mean a sold-out category could never
 * return.
 */

import type {
  AdminCategoryDto,
  CategoryLevel,
  BrandDto,
  CampaignDto,
  CategoryDto,
  ProductReviewsDto,
  ReviewDto,
} from '@outlet/types';
import { Db, allowListed, fromBool, nowIso } from '../lib/sql';

export async function listBrands(db: Db): Promise<BrandDto[]> {
  const rows = await db.all<{
    id: string;
    name: string;
    slug: string;
    description: string | null;
    logoUrl: string | null;
    isFeatured: number;
    productCount: number;
  }>(
    `SELECT b."id", b."name", b."slug", b."description", b."logoUrl", b."isFeatured",
            COUNT(p."id") AS "productCount"
       FROM "brands" b
       LEFT JOIN "products" p ON p."brandId" = b."id" AND p."status" = 'ACTIVE'
      WHERE b."isActive" = 1
      GROUP BY b."id"
      ORDER BY b."isFeatured" DESC, b."name"`,
  );
  return rows.map((row) => ({
    ...row,
    isFeatured: fromBool(row.isFeatured),
    // Generated by the media route when the bucket has no object, so a brand
    // tile is never an empty box.
    imageUrl: `/media/brands/${row.slug}.svg`,
  }));
}

interface CategoryRow {
  id: string;
  name: string;
  slug: string;
  parentId: string | null;
  pathSegment: string;
  position: number;
  isActive: number;
  targetGroup: CategoryDto['targetGroup'];
  sizeChartGroup: string | null;
  description: string | null;
  directProductCount: number;
  totalProductCount: number;
}

/** Every category with its own product counts; the tree is assembled in memory. */
async function readCategoryRows(db: Db): Promise<CategoryRow[]> {
  return db.all<CategoryRow>(
    `SELECT c."id", c."name", c."slug", c."parentId", c."pathSegment", c."position",
            c."isActive", c."targetGroup", c."sizeChartGroup", c."description",
            COUNT(CASE WHEN p."status" = 'ACTIVE'
                        AND EXISTS (SELECT 1 FROM "product_variants" v
                                      JOIN "inventory_balances" ib ON ib."variantId" = v."id"
                                     WHERE v."productId" = p."id" AND v."isEnabled" = 1
                                       AND ib."onHandQuantity" > ib."reservedQuantity")
                       THEN 1 END) AS "directProductCount",
            COUNT(p."id") AS "totalProductCount"
       FROM "categories" c
       LEFT JOIN "products" p ON p."categoryId" = c."id"
      GROUP BY c."id"
      ORDER BY c."position", c."name"`,
  );
}

interface TreeNode extends CategoryRow {
  children: TreeNode[];
  subtreeProductCount: number;
  /** Segments from the department down to this node. */
  path: string[];
  level: CategoryLevel;
}

const LEVELS: CategoryLevel[] = ['department', 'category', 'subcategory'];

function assembleTree(rows: CategoryRow[]): TreeNode[] {
  const nodes = new Map<string, TreeNode>();
  for (const row of rows) {
    nodes.set(row.id, {
      ...row,
      children: [],
      subtreeProductCount: 0,
      path: [],
      level: 'department',
    });
  }

  const roots: TreeNode[] = [];
  for (const node of nodes.values()) {
    if (node.parentId && nodes.has(node.parentId)) nodes.get(node.parentId)!.children.push(node);
    else roots.push(node);
  }

  // Depth-first, so a parent's count includes everything beneath it, and so a
  // node's path and level are known from its ancestry rather than stored.
  const walk = (node: TreeNode, ancestry: string[]): number => {
    node.path = [...ancestry, node.pathSegment];
    node.level = LEVELS[Math.min(node.path.length - 1, LEVELS.length - 1)];
    node.subtreeProductCount =
      node.directProductCount +
      node.children.reduce((sum, child) => sum + walk(child, node.path), 0);
    return node.subtreeProductCount;
  };
  for (const root of roots) walk(root, []);

  const sort = (list: TreeNode[]) => {
    list.sort((a, b) => a.position - b.position || a.name.localeCompare(b.name));
    for (const node of list) sort(node.children);
  };
  sort(roots);
  return roots;
}

/** The storefront link for a node — assembled once, so no caller rebuilds it. */
const hrefFor = (path: string[]): string => `/shop/${path.join('/')}`;

/** Tile artwork, rendered by the media route when the bucket has no object. */
const categoryImage = (slug: string): string => `/media/categories/${slug}.svg`;

/**
 * The customer-facing tree: whatever an administrator has left switched on.
 *
 * Visibility is `isActive` and nothing else. This used to also require stock —
 * a category with no available products removed itself from the menu — which
 * meant the navigation rearranged itself as things sold out and an
 * administrator had no way to keep a category on the menu, nor any way to tell
 * from the shop why one had gone. Emptiness is still *reported* in the admin
 * tree, as information; it no longer decides anything. A category the shop
 * should not show is one somebody switched off.
 */
export async function listCategories(db: Db): Promise<CategoryDto[]> {
  const roots = assembleTree(await readCategoryRows(db));

  const visible = (node: TreeNode): CategoryDto | null => {
    if (!fromBool(node.isActive)) return null;
    const children = node.children
      .map(visible)
      .filter((child): child is CategoryDto => child !== null);
    return {
      id: node.id,
      name: node.name,
      slug: node.slug,
      parentId: node.parentId,
      pathSegment: node.pathSegment,
      path: node.path,
      href: hrefFor(node.path),
      position: node.position,
      targetGroup: node.targetGroup,
      level: node.level,
      sizeChartGroup: node.sizeChartGroup as CategoryDto['sizeChartGroup'],
      productCount: node.subtreeProductCount,
      imageUrl: categoryImage(node.slug),
      children,
    };
  };

  return roots.map(visible).filter((node): node is CategoryDto => node !== null);
}

/** The admin tree: everything, with Hidden and Empty reported separately. */
export async function listCategoriesForAdmin(db: Db): Promise<AdminCategoryDto[]> {
  const roots = assembleTree(await readCategoryRows(db));

  const map = (node: TreeNode, ancestorsActive: boolean): AdminCategoryDto => {
    const isActive = fromBool(node.isActive);
    const reachable = isActive && ancestorsActive;
    // Hidden and empty are different things and only one of them is a
    // decision: `hidden` means somebody switched it off and the shop will not
    // show it; `empty` means it is on the menu with nothing behind it yet,
    // which is a note to whoever manages stock, not a reason to hide it.
    const status: AdminCategoryDto['status'] = !isActive
      ? 'hidden'
      : node.subtreeProductCount === 0
        ? 'empty'
        : 'active';
    return {
      id: node.id,
      name: node.name,
      slug: node.slug,
      parentId: node.parentId,
      pathSegment: node.pathSegment,
      path: node.path,
      href: hrefFor(node.path),
      position: node.position,
      targetGroup: node.targetGroup,
      level: node.level,
      sizeChartGroup: node.sizeChartGroup as AdminCategoryDto['sizeChartGroup'],
      description: node.description,
      isActive,
      status,
      // Whether a shopper can reach it, which is now purely a question of
      // switches — its own and its ancestors'. An empty category is still
      // reachable; `status` says it has nothing in it.
      isVisible: reachable,
      directProductCount: node.directProductCount,
      productCount: node.subtreeProductCount,
      totalProductCount: node.totalProductCount,
      children: node.children.map((child) => map(child, reachable)),
    };
  };

  return roots.map((root) => map(root, true));
}

/** Resolves /shop/women/clothing/dresses to the trail of categories it names. */
export async function resolveCategoryPath(
  db: Db,
  segments: string[],
): Promise<CategoryDto[] | null> {
  if (segments.length === 0 || segments.length > 3) return null;
  const rows = await readCategoryRows(db);
  const byParent = new Map<string | null, CategoryRow[]>();
  for (const row of rows) {
    const list = byParent.get(row.parentId) ?? [];
    list.push(row);
    byParent.set(row.parentId, list);
  }

  const trail: CategoryRow[] = [];
  let parentId: string | null = null;
  for (const segment of segments) {
    const match: CategoryRow | undefined = (byParent.get(parentId) ?? []).find(
      (row) => row.pathSegment === segment && fromBool(row.isActive),
    );
    if (!match) return null;
    trail.push(match);
    parentId = match.id;
  }

  // The tree is assembled anyway, because the trail has to report the rolled-up
  // product count each node carries, not just its own.
  const byId = new Map<string, TreeNode>();
  const walk = (nodes: TreeNode[]) => {
    for (const node of nodes) {
      byId.set(node.id, node);
      walk(node.children);
    }
  };
  walk(assembleTree(rows));

  return trail.map((row) => {
    const node = byId.get(row.id);
    const path = node?.path ?? [row.pathSegment];
    return {
      id: row.id,
      name: row.name,
      slug: row.slug,
      parentId: row.parentId,
      pathSegment: row.pathSegment,
      path,
      href: hrefFor(path),
      position: row.position,
      targetGroup: row.targetGroup,
      level: node?.level ?? 'department',
      sizeChartGroup: row.sizeChartGroup as CategoryDto['sizeChartGroup'],
      productCount: node?.subtreeProductCount ?? 0,
      imageUrl: categoryImage(row.slug),
      children: [],
    };
  });
}

// --- Campaigns ---------------------------------------------------------------

export async function listCampaigns(db: Db, status?: string): Promise<CampaignDto[]> {
  const clauses = [`"isVisible" = 1`];
  const bindings: string[] = [];
  if (status) {
    clauses.push(`"status" = ?`);
    bindings.push(status);
  } else {
    // Default view is what a shopper can act on: running or about to run.
    clauses.push(`"status" IN ('ACTIVE', 'SCHEDULED')`);
  }

  const rows = await db.all<CampaignDto & { productCount: number }>(
    `SELECT c."id", c."title", c."slug", c."shortDescription", c."description", c."coverImageUrl",
            c."startsAt", c."endsAt", c."status", c."position", c."seoTitle", c."seoDescription",
            (SELECT COUNT(*) FROM "campaign_products" cp WHERE cp."campaignId" = c."id") AS "productCount"
       FROM "campaigns" c
      WHERE ${clauses.join(' AND ')}
      ORDER BY (CASE WHEN c."status" = 'ACTIVE' THEN 0 ELSE 1 END), c."position", c."startsAt"`,
    ...bindings,
  );
  return rows;
}

export async function getCampaign(db: Db, slug: string): Promise<CampaignDto | null> {
  return db.first<CampaignDto>(
    `SELECT "id", "title", "slug", "shortDescription", "description", "coverImageUrl",
            "startsAt", "endsAt", "status", "position", "seoTitle", "seoDescription"
       FROM "campaigns" WHERE "slug" = ? AND "isVisible" = 1`,
    slug,
  );
}

// --- Reviews -----------------------------------------------------------------

const REVIEW_SORTS = {
  newest: `"createdAt" DESC`,
  oldest: `"createdAt" ASC`,
  rating_desc: `"rating" DESC, "createdAt" DESC`,
  rating_asc: `"rating" ASC, "createdAt" DESC`,
  helpful: `"helpfulCount" DESC, "createdAt" DESC`,
} as const;

/**
 * A product's reviews, with the histogram.
 *
 * Only reviews with written text are listed, but *every* published rating
 * counts toward the average and the distribution — which is how a real store
 * works, and why the summary is computed from rows rather than read off a
 * denormalised counter that could drift.
 */
export async function getProductReviews(
  db: Db,
  slug: string,
  params: { sort?: string; page?: string; pageSize?: string },
): Promise<ProductReviewsDto | null> {
  const product = await db.first<{ id: string }>(
    `SELECT "id" FROM "products" WHERE "slug" = ?`,
    slug,
  );
  if (!product) return null;

  const summary = await db.all<{ rating: number; n: number; verified: number }>(
    `SELECT "rating", COUNT(*) AS "n", SUM("isVerifiedPurchase") AS "verified"
       FROM "product_reviews"
      WHERE "productId" = ? AND "status" = 'PUBLISHED'
      GROUP BY "rating"`,
    product.id,
  );

  const distribution: Record<string, number> = { '1': 0, '2': 0, '3': 0, '4': 0, '5': 0 };
  let reviewCount = 0;
  let ratingSum = 0;
  let verifiedCount = 0;
  for (const row of summary) {
    distribution[String(row.rating)] = row.n;
    reviewCount += row.n;
    ratingSum += row.rating * row.n;
    verifiedCount += row.verified ?? 0;
  }

  const pageSize = Math.max(1, Math.min(50, Number(params.pageSize) || 10));
  const total = await db.count(
    `SELECT COUNT(*) AS "c" FROM "product_reviews"
      WHERE "productId" = ? AND "status" = 'PUBLISHED' AND LENGTH(TRIM("body")) > 0`,
    product.id,
  );
  const totalPages = Math.ceil(total / pageSize);
  const page = totalPages === 0 ? 1 : Math.min(Math.max(1, Number(params.page) || 1), totalPages);

  const items = await db.all<ReviewDto>(
    `SELECT "id", "rating", "title", "body", "authorName", "isVerifiedPurchase",
            "helpfulCount", "createdAt", "adminReply", "adminReplyAt"
       FROM "product_reviews"
      WHERE "productId" = ? AND "status" = 'PUBLISHED' AND LENGTH(TRIM("body")) > 0
      ORDER BY ${allowListed(params.sort, REVIEW_SORTS, 'newest')}
      LIMIT ? OFFSET ?`,
    product.id,
    pageSize,
    (page - 1) * pageSize,
  );

  return {
    ratingAverage: reviewCount > 0 ? Math.round((ratingSum / reviewCount) * 10) / 10 : null,
    reviewCount,
    distribution,
    verifiedCount,
    items: items.map((item) => ({
      ...item,
      isVerifiedPurchase: fromBool(item.isVerifiedPurchase),
    })),
    total,
    page,
    pageSize,
    totalPages,
  };
}

// --- CMS ---------------------------------------------------------------------

export async function getContentPage(db: Db, key: string) {
  return db.first<{ key: string; title: string; body: string; updatedAt: string }>(
    `SELECT "key", "title", "body", "updatedAt" FROM "content_pages" WHERE "key" = ?`,
    key,
  );
}

/**
 * The CMS pages, bodies included.
 *
 * The admin editor loads this list and binds the selected page's `body`
 * straight into its textarea — it does not fetch the page again — so omitting
 * the column opens every page blank and saves the blank back over it. There
 * are a handful of these rows and only an administrator can read them, so the
 * payload is not a reason to leave the column out.
 */
export async function listContentPages(db: Db) {
  return db.all<{ key: string; title: string; body: string; updatedAt: string }>(
    `SELECT "key", "title", "body", "updatedAt" FROM "content_pages" ORDER BY "key"`,
  );
}

/** Homepage rails. One query per rail, each already limited. */
export async function homepageCampaign(db: Db): Promise<CampaignDto | null> {
  const now = nowIso();
  return db.first<CampaignDto>(
    `SELECT "id", "title", "slug", "shortDescription", "description", "coverImageUrl",
            "startsAt", "endsAt", "status", "position", "seoTitle", "seoDescription"
       FROM "campaigns"
      WHERE "status" = 'ACTIVE' AND "isVisible" = 1 AND "startsAt" <= ? AND "endsAt" > ?
      ORDER BY "position" LIMIT 1`,
    now,
    now,
  );
}
