#!/usr/bin/env node
/**
 * `pnpm db:reset-demo` — empties the demo database and seeds it again.
 *
 *   node scripts/reset-demo.mjs --local
 *   node scripts/reset-demo.mjs --remote --yes-really
 *
 * This deletes every row, so the remote form is guarded twice over: the
 * environment has to identify itself as a demo/staging one, and the caller has
 * to say --yes-really. Neither guard alone is something you can satisfy by
 * accident, and the intent is that a production database is unreachable from
 * here regardless of what is typed.
 *
 * The schema is left in place; only data is cleared. Rebuilding the schema is
 * `wrangler d1 migrations apply`, which is a different operation with a
 * different blast radius.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { reportCounts, writeSeedSql } from './build-seed-sql.mjs';
import { DATABASE_NAME, assertResettable, resolveTarget, runWrangler } from './lib/wrangler.mjs';

const APP_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const argv = process.argv.slice(2);

const target = resolveTarget(argv);
assertResettable(target, argv);

/*
 * Children before parents, so foreign keys are satisfied at every step rather
 * than relying on cascades — a cascade that silently does not fire is how a
 * "reset" leaves orphans behind.
 */
const TABLES_IN_DELETION_ORDER = [
  'shipment_events',
  'shipments',
  'refunds',
  'return_items',
  'return_requests',
  'payment_events',
  'payments',
  'order_status_history',
  'order_items',
  'inventory_reservations',
  'orders',
  'cart_items',
  'carts',
  'wishlist_items',
  'wishlists',
  'inventory_movements',
  'inventory_balances',
  'campaign_products',
  'campaigns',
  'product_reviews',
  'product_images',
  'product_attribute_values',
  'product_attributes',
  'product_variants',
  'products',
  'categories',
  'brands',
  'coupons',
  'promotions',
  'notifications',
  'newsletter_subscriptions',
  'customer_support_notes',
  'audit_logs',
  'uploaded_files',
  'background_job_records',
  'content_pages',
  'site_settings',
  'user_roles',
  'role_permissions',
  'roles',
  'permissions',
  'addresses',
  'user_sessions',
  'users',
];

const truncatePath = join(APP_ROOT, '.seed', 'reset.sql');
mkdirSync(dirname(truncatePath), { recursive: true });
writeFileSync(
  truncatePath,
  [
    '-- Generated by scripts/reset-demo.mjs. Clears data; leaves the schema.',
    ...TABLES_IN_DELETION_ORDER.map((table) => `DELETE FROM "${table}";`),
    '',
  ].join('\n'),
  'utf8',
);

console.log(`Clearing the ${target.label} database "${DATABASE_NAME}"…`);
runWrangler(['d1', 'execute', DATABASE_NAME, target.flag, `--file=${truncatePath}`, '--yes'], APP_ROOT);

console.log('\nRe-seeding…');
const { path, counts, generated } = writeSeedSql();
runWrangler(['d1', 'execute', DATABASE_NAME, target.flag, `--file=${path}`, '--yes'], APP_ROOT);

console.log('\nReset complete.\n');
reportCounts(counts);

if (generated.length > 0) {
  console.log('\nNew demo passwords — copy them now, they are not stored:\n');
  for (const [label, value] of generated) console.log(`  ${label}\n    ${value}\n`);
}
