#!/usr/bin/env node
/**
 * Writes the generated catalogue artwork to `apps/storefront/public/artwork`.
 *
 * The demo build used to inline every image as a `data:` URI. That works in the
 * browser but not through Next's static export: a ~10 KB URI embedded in an
 * HTML attribute and again in the RSC payload came back corrupted, and every
 * product image on the exported site failed to decode. Writing real files also
 * happens to be the better architecture — it takes ~350 KB of duplicated URI
 * out of each product page, lets images be cached across pages, and matches the
 * API-backed deployment, where these same keys are S3/R2 objects.
 *
 * Output is derived entirely from packages/catalog, so it is disposable: the
 * directory is gitignored and regenerated by `predev` / `prebuild`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');

const catalogDist = path.join(root, 'packages/catalog/dist');
if (!fs.existsSync(path.join(catalogDist, 'artwork.js'))) {
  console.error('packages/catalog is not built — run `pnpm --filter @outlet/catalog build` first.');
  process.exit(1);
}

const art = require(path.join(catalogDist, 'artwork.js'));
const spec = require(path.join(catalogDist, 'spec.js'));

const OUT = path.join(root, 'apps/storefront/public/artwork');
fs.rmSync(OUT, { recursive: true, force: true });

let written = 0;
const write = (relative, svg) => {
  const file = path.join(OUT, relative);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, svg);
  written += 1;
};

for (const product of spec.PRODUCTS) {
  const brand = spec.BRANDS.find((b) => b.slug === product.brand);
  for (const color of product.colors) {
    for (const view of art.PRODUCT_VIEWS) {
      write(
        `products/${product.slug}/${color.toLowerCase()}-${view}.svg`,
        art.productArtworkSvg({
          shape: product.shape,
          color,
          brandName: brand?.name ?? product.brand,
          productName: product.name,
          view,
        }),
      );
    }
  }
}

for (const category of spec.CATEGORIES) {
  write(`categories/${category.slug}.svg`, art.categoryArtworkSvg(category.slug, category.name));
}

for (const brand of spec.BRANDS) {
  write(`brands/${brand.slug}.svg`, art.brandArtworkSvg(brand.name));
}

for (const campaign of spec.CAMPAIGNS) {
  const items = art.campaignArtworkItems(campaign.productSlugs, (slug) => {
    const found = spec.PRODUCTS.find((p) => p.slug === slug);
    return found ? { shape: found.shape, colors: found.colors } : undefined;
  });
  write(`campaigns/${campaign.slug}.svg`, art.campaignArtworkSvg(campaign.slug, items));
}

console.log(`Generated ${written} artwork files in apps/storefront/public/artwork`);
